###
# Delete Datastore (Soft delete)
DELETE http://localhost:5012/api/datastore/<datastore_id>

###
# Get datastore list
GET http://localhost:5012/api/datastore/list?datastore_id=<datastore_id>
Content-type: application/json

###
# Update Datastore 
PUT http://localhost:5012/api/datastore/DSTR0ELLPV56XT94P5Q5I3P9L
Content-Type: application/json

{
  "name":"dssto3"
}
###
# Get a datastore with a filter. Can accept multiple args
GET http://localhost:5012/api/dataset?dataset_id=DSET1W7I1PE3UU9U57X5BEJ1G
Content-type: application/json

###
# Create Datastore via datastore-management-service
POST http://localhost:5012/api/dataset
Content-Type: application/json

{
  "name": "s2",
  "description": "s2 desc",
  "datastore_id": "DSTR0ELLPV56XT94P5Q5I3P9L"
  
}
###
# Insert datastore record directly to dao-service (must be running)
POST http://localhost:5010/api/create
Content-Type: application/json

{
    "table_name": "datastore",
     "payload": {
        "name": "test2",
        "description": "test2",
        "path": "/tmp"
        },
     "service": "datastore-management-service",
     "request_id": "df8123"
}